# Generated by Django 3.2.9 on 2022-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
