# Generated by Django 3.2.9 on 2022-08-19 04:13

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20220816_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_published',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='time_published',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='User<built-in function id>', max_length=24),
        ),
    ]
