# Generated by Django 3.2.9 on 2022-08-19 04:15

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20220819_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_published',
            field=models.DateTimeField(default=datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_published',
            field=models.DateTimeField(default=datetime.now),
        ),
    ]
