# Generated by Django 3.2.9 on 2022-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220819_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
