# Generated by Django 3.2.9 on 2022-08-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20220819_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='raw_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='raw_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='raw_title',
        ),
    ]
